language: python

python:
  - "2.7"

# command to install dependencies
install:
  - "pip install discover"
  - "pip install rdflib"
  - "pip install networkx"
  - "git clone https://github.com/NeuralEnsemble/libNeuroML.git"
  - "cd libNeuroML"
  - "python setup.py install"
  - "cd .."
  - "pip install pint"
  - "pip install . --use-mirrors"


script:  
  - python -m unittest discover -s tests
