language: python

python:
  - "2.7"

# command to install dependencies
# had to split requirements.txt into
#  TWO files because they install all or none
#  and dependencies installed later don't know
#  about dependencies installed earlier in the process
install:
  - "pip install coveralls"
  - "python setup.py install"


script:
# Old, pre-pytest technique.
# - "coverage run --source=PyOpenWorm tests/test.py"

# Codespeed, default values for variables that break server
# - "py.test --cov=PyOpenWorm --code-speed-submit=\"http://pyopenworm.pythonanywhere.com/\" ----environment=\"Dual Core\" --branch=\"default\" -commit=\"0\""

# Codespeed, how it will work once Codespeed is fixed.
# - "py.test --cov=PyOpenWorm --code-speed-submit=\"http://pyopenworm.pythonanywhere.com/\" ----environment=\"Dual Core\" --branch=\"`git symbolic-ref HEAD | sed -e 's,refs/heads/,,'`\" -commit=\"t rev-parse HEAD`\""

  - "py.test --cov=PyOpenWorm --ignore=tests/InferenceTest.py"
  

after_success:
  - "coveralls"
