language: python

python:
  - "2.7"

# command to install dependencies
# had to split requirements.txt into
#  TWO files because they install all or none
#  and dependencies installed later don't know 
#  about dependencies installed earlier in the process
install:
  - "pip install -r pre-reqs.txt"
  - "pip install -r requirements.txt"
  - "python setup.py develop"
  - "rm tests/test_Sleepycat.conf"
     

script:  
  - ./runtests.sh
