language: python

python:
  - "2.7"

# command to install dependencies
install:
  - "pip install discover"
  - "pip install rdflib"
  - "pip install networkx"
  - "pip install libNeuroML"
  - "pip install pint"
  - "pip install tables"
  - "pip install . --use-mirrors"


script:  
  - python -m unittest discover -s tests
