language: python

python:
  - "2.7"

# command to install dependencies
# had to split requirements.txt into
#  TWO files because they install all or none
#  and dependencies installed later don't know 
#  about dependencies installed earlier in the process
install:
  - "python setup.py develop"
     

script:  
  - "python tests/test.py"
